### ISSUE TITLE
READMEの整備

### ISSUE THREAD

**Issue by cffnpwr** [CaffeBreak/coffee-break#25]
あとから開発に参加する人がREADMEを見れば開発環境を構築できるようにするべき

**Comment by AOI-1up** [comment]
@cffnpwr README 置くのはリポジトリのトップ？それとも frontend とか個別の場所？

**Comment by cffnpwr** [comment]
リポジトリのトップは絶対

**Comment by yanbaru1331** [comment]
TOPは概要と構築の仕方は欲しいね
